name: Checkmarx One Scan

on:
  pull_request:
  workflow_dispatch:
  workflow_call:
inputs:
  tag:
    description: 'Next release tag'
    required: true
    type: string
  channels:
    description: 'Channels to publish development releases'
    required: false
    type: string

jobs:
  cx-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3.11.0
        with:
          distribution: zulu
          java-version: 11
      - name: Testing if prerelase works
        env:
          prerelease: ${{ inputs.channels != '' && inputs.channels != null }}
        run: |
          echo "prerelease: $prerelease"
      - name: Checkmarx One CLI Action
        uses: checkmarx/ast-github-action@main
        with:
          base_uri: ${{ secrets.AST_RND_SCANS_BASE_URI }}
          cx_tenant: ${{ secrets.AST_RND_SCANS_TENANT }}
          cx_client_id: ${{ secrets.AST_RND_SCANS_CLIENT_ID }}
          cx_client_secret: ${{ secrets.AST_RND_SCANS_CLIENT_SECRET }}
          additional_params: --tags galactica-team --file-include *.gradle,gradlew
