name: AST Jetbrains Plugin Scan

on: [ pull_request, workflow_dispatch ]

jobs:
  cx-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx AST CLI Action
        uses: checkmarxDev/ast-github-action@master
        with:
          project_name: ast-jetbrains-plugin
          branch: master
          base_uri: ${{ secrets.CX_BASE_URI }}
          cx_tenant: ${{ secrets.CX_TENANT }}
          cx_apikey: ${{ secrets.CX_APIKEY }}
          additional_params: --tags galactica-team
