name: Nightly Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  set_tag:
    runs-on: ubuntu-latest
    outputs:
      tag_version: ${{ steps.tagname.outputs.tag_version }}
      ast_version: ${{ steps.tagname.outputs.ast_version }}
      devassist_version: ${{ steps.tagname.outputs.devassist_version }}
    steps:
      - name: Create version
        id: tagname
        run: |
          TS=$(date +%s)
          echo "tag_version=2.0.${TS}" >> "$GITHUB_OUTPUT"
          echo "ast_version=2.0.${TS}" >> "$GITHUB_OUTPUT"
          echo "devassist_version=1.0.${TS}" >> "$GITHUB_OUTPUT"
      - name: Print version
        run: echo "created version ${{ steps.tagname.outputs.tag_version }}"
  nightly:
    needs: set_tag
    uses: Checkmarx/ast-jetbrains-plugin/.github/workflows/release.yml@feature/release-pipeline-v2
    with:
      tag: ${{ needs.set_tag.outputs.tag_version }}
      ast_version: ${{ needs.set_tag.outputs.ast_version }}
      devassist_version: ${{ needs.set_tag.outputs.devassist_version }}
      releaseType: "checkmarx"
      rchannels: "nightly"
    secrets: inherit
