name: Test UI Windows

on:
  workflow_dispatch:

env:
  CX_BASE_URI: ${{ secrets.CX_BASE_URI }}
  CX_APIKEY: ${{ secrets.CX_APIKEY }}
  CX_TENANT: ${{ secrets.CX_TENANT }}
  CX_TEST_REPO: ${{ secrets.CX_TEST_REPO }}
  CX_TEST_SCAN: ${{ secrets.CX_TEST_SCAN }}
  CX_TEST_BRANCH: ${{ secrets.CX_TEST_BRANCH }}
  CX_TEST_PROJECT: ${{ secrets.CX_TEST_PROJECT }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  testUI:
    runs-on: windows-latest
    steps:
      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v3
      # Setup Java 11 environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 11
      - name: Setup FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v1
        with:
          # Not strictly necessary, but it may prevent rate limit
          # errors especially on GitHub-hosted macos machines.
          token: ${{ secrets.GITHUB_TOKEN }}
      # Perform clean before testing
      - name: Clean
        run: ./gradlew clean
      # Run IDEA prepared for UI testing
      - name: Run IDE
        run: |
          mkdir -p build/reports
          Set-DisplayResolution -Width 1920 -Height 1080 -Force
          start .\runIdeForUiTests.bat
      # Wait for IDEA to be started
      - name: Health Check
        run: curl.exe --fail -sv --retry "15" --retry-delay "10" --retry-connrefused "http://127.0.0.1:8580"
      # Run tests
      - name: Tests
        run: |
          Set-DisplayResolution -Width 1920 -Height 1080 -Force
          ./gradlew test -PuiWaitDuration=800 --info --tests com.checkmarx.intellij.ui*
      # Save video if tests fail
      - name: Move video
        if: ${{ failure() }}
        run: mv video build/reports
      # Save report if tests fail
      - name: Save fails report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-fails-report
          path: build/reports
      # Save idea log if tests fail
      - name: Save idea log
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: idea.log
          path: idea.log
