name: Run Integration Tests
on:
  workflow_dispatch
env:
  CX_BASE_URI: ${{ secrets.CX_BASE_URI }}
  CX_APIKEY: ${{ secrets.CX_APIKEY }}
  CX_TENANT: ${{ secrets.CX_TENANT }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  testIntegration:
    runs-on: ubuntu-latest

    steps:

      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v2.3.4

      # Setup Java 11 environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 11

      # Run tests
      - name: Tests
        run: ./gradlew test -i --tests com.checkmarx.intellij.standard*

      # Save report if tests fail
      - name: Save fails report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-fails-report-integration
          path: |
            build/reports
